### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by bobvanderlinden** [bobvanderlinden/ld45#5]
- [x] doodgaan onderin level
- [x] eindscherm voor doodgaan
- [x] vallen automagisch
- [x] groeien door fruit
- [x] boom met gouden appel
- [x] win eindscherm
- [ ] levels
- [x] Fix level loading
- [x] Fix multi cell collision on blocks
- [x] Hoofd mee laten draaien met richting
- [x] Camera reset bij start
- [x] Tree in background
- [x] Titelscherm
- [ ] Geluid
- [ ] Muziek
- [x] dooddetectie
- [x] staart
- [x] clouds
- [ ] grass

**Comment by nickschot** [comment]
dood-detectie is er nu, doet wel alleen nog console spam.
